= A Very Small Language Model
Jez Higgins, JezUK Ltd
2024-10-28

== Abstract

There are lots of things in software that seem kind of amazing, even to people who work in software. Compilers & interpreters, operating systems, windowing systems are obvious choices, as are lots of games stuff. These are, however, all pretty large topics. You can’t write an operating system in even a 90 minute session. I can’t anyway.

My phone keyboard keeps asking me again if I want to turn on some kind of AI assistant to "boost productivity" and "unlock creativity". I continue to say no, but this rebranding of "next word prediction" as "AI assistance" and thus grouping in the same bucket as the ChatGPTs and the Claudes and what have you stoke up the idea that text prediction is a difficult problem, best left to the big brains at Google or Apple or Microsoft with their shiny offices and free lunches in Silicon Valley and Redmond.

I reject that idea. We're all programmers, we can all write the magical bits of software. We can write a text prediction engine from a standing start in an hour. We'll then see how we can enhance our very small language model, and maybe even "boost productivity" and "unlock creativity".

== Session Content

Obviously we're going to have a look at Markov chains, how to populate a Markov chain from a text corpus, and how to use the model that it forms to make predictions.

We'll look at how varying the length of the input token sequence affects the quality of the predictions. We'll also look at how changing the seed corpus affect the predictions (eg Jane Austen vs Conan Doyle vs a big collection of npm modules), We'll consider, (but not implement) other things we could use to influence our model (punctuation, parts of speech tagging, stemming, synonyms). We'll also discuss at what point rolling the dice against a Markov chain start to cross-over into "artificial intelligence".

The code I have written is in JavaScript, because everyone can read it, and it's pretty concise on screen. I'm happy to rework in another language if people have strong preferences for something else.
