= A Very Small Language Model
Jez Higgins, JezUK Ltd
2024-10-28

== Abstract

There are lots of things in software that seem kind of amazing, even to people who work in software. Compilers & interpreters, operating systems, windowing systems are obvious choices, as are lots of games stuff. These are, however, all pretty large topics. You can’t write an operating system in even a 90 minute session. I can’t anyway.

My phone keyboard keeps asking me again and again if I want to turn on some kind of AI assistant to "boost productivity" and "unlock creativity". I continue to say no, but it got me thinking. This rebranding of "next word prediction" as "AI assistance" groups this tech in the same bucket as the ChatGPTs and the Claudes and what have you and stokes up the idea that text prediction is a difficult problem, something best left to the big brains at Google or Apple or Microsoft with their shiny offices and free lunches in Silicon Valley and Redmond.

I reject that idea. I think this tech is something any programmer can do. We can write a text prediction engine from a standing start in an hour. In this talk, I'll show attendees how to so just that, as well as enhance our very small language model, and maybe even "boost productivity" and "unlock creativity".

== Session Content

Obviously we're going to have a look at Markov chains, how to populate a Markov chain from a text corpus, and how to use the model that it forms to make predictions.

Next we'll look at how adding more data gives us better predictions. We'll also look at what changing the data does to the predictions (taking in Jane Austen, Conan Doyle and a big collection of npm modules). We'll also consider other things we could use to influence our model (such as punctuation, tagging, stemming, synonyms etc). We'll also discuss where this kind of work crosses over into the realm of "artificial intelligence".

The code I have written is in JavaScript, because everyone can read it, and it's pretty concise on screen. I'm happy to rework in another language if people have strong preferences for something else.

== Speaker

Jez Higgins is a freelance software grandad. He mucks in with programming, lends a hand with build and deployment processes, provides a leg up with TDD practices, and keeps an eye on the young 'uns so they don’t get trapped down the old mine shaft. He won Fishguard & Goodwick Hockey Club's Most Dedicated Player award for the 2023-24 season.
